import PDFDocument from 'pdfkit'
import { Readable } from 'stream'

interface ReceiptData {
  reference: string
  service: string
  product: string
  recipient: string
  amount: number
  fee: number
  total: number
  date: string
  status: string
  userName: string
}

export class ReceiptService {
  
  /**
   * Generates a Normal Receipt PDF (full details with price)
   */
  async generateNormalReceipt(data: ReceiptData): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ size: 'A4', margin: 50 })
      const chunks: Buffer[] = []
      
      doc.on('data', (chunk: Buffer) => chunks.push(chunk))
      doc.on('end', () => resolve(Buffer.concat(chunks)))
      doc.on('error', reject)
      
      // Watermark (repeated across page)
      this.addWatermark(doc)
      
      // Header
      doc.fontSize(24).fillColor('#082B72').text('DEPAYHUB', { align: 'center' })
      doc.moveDown(0.3)
      doc.fontSize(10).fillColor('#999999').text('Digital Payment & VTU Platform', { align: 'center' })
      doc.moveDown(1.5)
      
      // Divider
      doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#E5E7EB').stroke()
      doc.moveDown(1)
      
      // Receipt Title
      doc.fontSize(16).fillColor('#082B72').text('Transaction Receipt', { align: 'center' })
      doc.moveDown(1)
      
      // Status Badge
      const statusColor = data.status === 'SUCCESSFUL' ? '#16A34A' : data.status === 'FAILED' ? '#DC2626' : '#F59E0B'
      doc.fontSize(12).fillColor(statusColor).text(data.status, { align: 'center' })
      doc.moveDown(1.5)
      
      // Details Table
      const details = [
        ['Service', data.service],
        ['Product', data.product],
        ['Recipient', data.recipient],
        ['Amount', `NGN ${data.amount.toLocaleString()}`],
        ['Fee', `NGN ${data.fee.toLocaleString()}`],
        ['Total', `NGN ${data.total.toLocaleString()}`],
        ['Reference', data.reference],
        ['Date', data.date],
        ['Status', data.status]
      ]
      
      details.forEach(([label, value]) => {
        const y = doc.y
        doc.fontSize(10).fillColor('#6B7280').text(label, 50, y, { width: 200 })
        doc.fontSize(10).fillColor('#111827').text(value, 250, y, { width: 295, align: 'right' })
        doc.moveDown(0.8)
      })
      
      doc.moveDown(1)
      doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#E5E7EB').stroke()
      doc.moveDown(1)
      
      // Footer
      doc.fontSize(8).fillColor('#9CA3AF').text('This receipt was generated by Depayhub. For support, contact support@depayhub.com', { align: 'center' })
      doc.moveDown(0.3)
      doc.fontSize(8).fillColor('#9CA3AF').text(`Generated: ${new Date().toISOString()}`, { align: 'center' })
      
      doc.end()
    })
  }
  
  /**
   * Generates a Share Receipt PDF (no price, masked recipient)
   */
  async generateShareReceipt(data: ReceiptData): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ size: 'A4', margin: 50 })
      const chunks: Buffer[] = []
      
      doc.on('data', (chunk: Buffer) => chunks.push(chunk))
      doc.on('end', () => resolve(Buffer.concat(chunks)))
      doc.on('error', reject)
      
      // Watermark
      this.addWatermark(doc)
      
      // Header
      doc.fontSize(24).fillColor('#082B72').text('DEPAYHUB', { align: 'center' })
      doc.moveDown(0.3)
      doc.fontSize(10).fillColor('#999999').text('Digital Payment & VTU Platform', { align: 'center' })
      doc.moveDown(1.5)
      
      doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#E5E7EB').stroke()
      doc.moveDown(1)
      
      doc.fontSize(16).fillColor('#082B72').text('Payment Confirmation', { align: 'center' })
      doc.moveDown(1)
      
      const statusColor = data.status === 'SUCCESSFUL' ? '#16A34A' : '#DC2626'
      doc.fontSize(12).fillColor(statusColor).text(data.status, { align: 'center' })
      doc.moveDown(1.5)
      
      // Mask recipient: 0801****5678
      const masked = data.recipient.length > 4
        ? data.recipient.substring(0, 4) + '****' + data.recipient.substring(data.recipient.length - 4)
        : data.recipient
      
      const details = [
        ['Service', data.service],
        ['Product', data.product],
        ['Recipient', masked],
        ['Reference', data.reference],
        ['Date', data.date],
        ['Status', data.status]
      ]
      
      details.forEach(([label, value]) => {
        const y = doc.y
        doc.fontSize(10).fillColor('#6B7280').text(label, 50, y, { width: 200 })
        doc.fontSize(10).fillColor('#111827').text(value, 250, y, { width: 295, align: 'right' })
        doc.moveDown(0.8)
      })
      
      doc.moveDown(1)
      doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#E5E7EB').stroke()
      doc.moveDown(1)
      
      doc.fontSize(8).fillColor('#9CA3AF').text('Powered by Depayhub', { align: 'center' })
      
      doc.end()
    })
  }
  
  private addWatermark(doc: PDFKit.PDFDocument) {
    doc.save()
    doc.fontSize(50).fillColor('#082B72').opacity(0.04)
    
    for (let y = 100; y < 800; y += 150) {
      for (let x = -50; x < 600; x += 250) {
        doc.text('DEPAYHUB', x, y, { continued: false })
      }
    }
    
    doc.opacity(1).restore()
    // Reset cursor to top
    doc.y = 50
  }
}

export const receiptService = new ReceiptService()
